-- Generated by drizzle-kit from src/modules/**/*.table.ts. Statement-breakpoint
-- markers are removed so the file runs as plain SQL on an empty MySQL 8 database.

CREATE TABLE `agent_actions` (
	`id` varchar(36) NOT NULL,
	`business_id` varchar(64) NOT NULL,
	`user_id` varchar(64) NOT NULL,
	`type` enum('WHATSAPP_RECEIVED') NOT NULL,
	`status` enum('pending','running','succeeded','failed') NOT NULL DEFAULT 'pending',
	`payload` json,
	`summary` varchar(255),
	`error_code` varchar(64),
	`attempts` int NOT NULL DEFAULT 0,
	`input_tokens` int NOT NULL DEFAULT 0,
	`output_tokens` int NOT NULL DEFAULT 0,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`started_at` timestamp,
	`finished_at` timestamp,
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `agent_actions_id` PRIMARY KEY(`id`)
);

CREATE TABLE `agent_configs` (
	`business_id` varchar(64) NOT NULL,
	`user_id` varchar(64) NOT NULL,
	`instructions` text NOT NULL,
	`assistant_name` varchar(64),
	`assistant_type` enum('receptionist') NOT NULL DEFAULT 'receptionist',
	`capabilities` json NOT NULL,
	`knowledge_base` mediumtext,
	`forbidden_keywords` json,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `agent_configs_business_id_user_id_pk` PRIMARY KEY(`business_id`,`user_id`)
);

CREATE TABLE `onboarding_requests` (
	`user_id` varchar(64) NOT NULL,
	`idempotency_key` varchar(128) NOT NULL,
	`request_hash` char(64) NOT NULL,
	`status` enum('in_progress','completed','failed') NOT NULL,
	`result` json,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `onboarding_requests_user_id_idempotency_key_pk` PRIMARY KEY(`user_id`,`idempotency_key`)
);

CREATE INDEX `agent_actions_tenant_idx` ON `agent_actions` (`business_id`,`user_id`,`created_at`);
CREATE INDEX `agent_actions_status_idx` ON `agent_actions` (`status`);
